seed: 42

models:
  separate: True
  policy:
    class: GaussianMixin
    clip_actions: True
    clip_mean_actions: True
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: -0.5
    network:
      - name: net
        input: OBSERVATIONS
        layers: [512, 256, 128]
        activations: elu
    output: ACTIONS
  value:
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [1024, 512, 256]
        activations: elu
    output: ONE

memory:
  class: RandomMemory
  memory_size: -1

agent:
  class: PPO
  rollouts: 64
  learning_epochs: 5
  mini_batches: 8
  discount_factor: 0.99
  lambda: 0.97
  learning_rate: 3.0e-04
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01
  observation_preprocessor: RunningStandardScaler
  observation_preprocessor_kwargs: null
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  value_preprocessor: null
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.002
  value_loss_scale: 1.0
  kl_threshold: 0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False
  experiment:
    directory: "tienkung2_lite_flat_v1"
    experiment_name: ""
    write_interval: 256
    checkpoint_interval: auto

trainer:
  class: SequentialTrainer
  timesteps: 600000
  environment_info: log
